[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"

[build.nixpacks]
nixPkgs = ["python3", "gcc", "gnumake", "sqlite"]
providers = ["node"]

[deploy]
startCommand = "cd backend && npm start"